### ISSUE TITLE
INVALID_BUFFER_SIZE when loading map

### ISSUE THREAD

**Issue by keneanung** [Delwing/node-mudlet-map-binary-reader#1]
Loading an already downloaded map produced this error:
```
RangeError [ERR_INVALID_BUFFER_SIZE]: Buffer size must be a multiple of 16-bits
    at new NodeError (node:internal/errors:371:5)
    at Buffer.swap16 (node:buffer:1135:11)
    at read (/workspaces/map-discord-bot/node_modules/qtdatastream/src/types.js:539:25)
    at readMap (/workspaces/map-discord-bot/node_modules/mudlet-map-binary-reader/map-reader.js:30:15)
    at readRoom (/workspaces/map-discord-bot/node_modules/mudlet-map-binary-reader/map-reader.js:173:19)
    at Object.module.exports [as read] (/workspaces/map-discord-bot/node_modules/mudlet-map-binary-reader/map-reader.js:221:17)
    at /workspaces/map-discord-bot/node_modules/discord-mudlet-map/maps/prepare-map.js:32:37
    at new Promise (<anonymous>)
    at /workspaces/map-discord-bot/node_modules/discord-mudlet-map/maps/prepare-map.js:31:9
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'ERR_INVALID_BUFFER_SIZE'
}
```
Restarting the bot did not throw the error again. nstead, it loaded the map just fine.

**Comment by Delwing** [comment]
I think after all reason was in downloader in bot, trying to read map before it was fully saved which was fixed. Never exeperienced issue again.
